{
  "_annotation": {
    "cve_id": "CVE-2024-21503",
    "reason": "Added CPE configurations because not yet analyzed by NVD.",
    "snapshot": "https://raw.githubusercontent.com/anchore/nvd-data-overrides/main/.snapshot/2024/CVE-2024-21503.json",
    "triage_notes": {
      "references": [
        "https://github.com/psf/black/releases/tag/24.3.0",
        "https://security.snyk.io/vuln/SNYK-PYTHON-BLACK-6256273",
        "https://github.com/psf/black/commit/f00093672628d212b8965a8993cee8bedf5fe9b8"
      ]
    }
  },
  "cve": {
    "configurations": [
      {
        "nodes": [
          {
            "cpeMatch": [
              {
                "criteria": "cpe:2.3:a:psf:black:*:*:*:*:*:*:*:*",
                "matchCriteriaId": "CC6C7A49-871D-588C-B96B-8637873B5C27",
                "versionEndExcluding": "24.3.0",
                "versionStartIncluding": "0",
                "vulnerable": true
              }
            ],
            "negate": false,
            "operator": "OR"
          }
        ]
      }
    ]
  }
}